# -*- coding: utf-8 -*-
"""EntregaFinal_Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7ZqeO4Ag0DZC70B0B268ZwAEMLFdJh9

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-reg-loads-v2.pkl'
modelo, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

# #Cargamos los datos futuros
# data = pd.read_csv("Predicciones.csv")
# data.head()

import streamlit as st
import pandas as pd

st.title('Predicción de cargas - Complex')

# ══════════════════════════════════════════════════════════════════
# PALAS — Uso de Disponibilidad por equipo
# ══════════════════════════════════════════════════════════════════
st.header('🚧 Palas — Uso de Disponibilidad')

equipos = [
    '6231','6232','6233','6234','6235','6236','6237','6238','6239',
    '6241','6242','6243','6244','6245','6246','6247','6248','6249',
    '6250','6260','6261','6262','6263','6264','6268','6269',
    '6449','6455','6457'
]

vals_palas = {}
cols = st.columns(3)
for i, eq in enumerate(equipos):
    with cols[i % 3]:
        vals_palas[f'UsodeDisp_{eq}'] = st.slider(
            f'Pala {eq}',
            min_value=0.0, max_value=1.0, value=0.0, step=0.01,
            key=f'pala_{eq}'
        )

# ══════════════════════════════════════════════════════════════════
# CAMIONES — por pit
# ══════════════════════════════════════════════════════════════════
st.header('🚛 Camiones — por Pit')

PITS = ['DESCANSO', 'DP5', 'EC', 'PRIBBENOW']

vals_camiones = {}
tabs = st.tabs(PITS)

for tab, pit in zip(tabs, PITS):
    with tab:
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            vals_camiones[f'QtyCamiones_{pit}'] = st.slider(
                'Qty Camiones',
                min_value=0.0, max_value=150.0, value=80.0, step=1.0,
                key=f'qty_{pit}'
            )
        with c2:
            vals_camiones[f'Disponibilidad_TKS_{pit}'] = st.slider(
                'Disponibilidad',
                min_value=0.0, max_value=1.0, value=0.80, step=0.01,
                key=f'disp_{pit}'
            )
        with c3:
            vals_camiones[f'UsodeDisp_TKS_{pit}'] = st.slider(
                'Uso de Disponibilidad',
                min_value=0.0, max_value=1.0, value=0.75, step=0.01,
                key=f'uso_{pit}'
            )
        with c4:
            # Nombre de columna varía según el pit (TiempoCiclo vs TiempoCiclo2)
            col_ciclo = (
                'TiempoCiclo_TKS_DESCANSO'   if pit == 'DESCANSO'  else
                'TiempoCiclo2_DP5'            if pit == 'DP5'       else
                'TiempoCiclo2_EC'             if pit == 'EC'        else
                'TiempoCiclo_TKS_PRIBBENOW'
            )
            vals_camiones[col_ciclo] = st.slider(
                'Ciclo (min)',
                min_value=20.0, max_value=42.0, value=30.0, step=0.1,
                key=f'ciclo_{pit}'
            )

# ══════════════════════════════════════════════════════════════════
# TURNO
# ══════════════════════════════════════════════════════════════════
st.header('⚙️ Turno')
turno = st.selectbox('Turno', ['D', 'N'])

# ══════════════════════════════════════════════════════════════════
# DATAFRAME — mismo esquema de columnas que el modelo espera
# ══════════════════════════════════════════════════════════════════
datos = {**vals_palas, **vals_camiones, 'turno': turno}
data = pd.DataFrame([datos])

# Verificación del orden de columnas esperado por el modelo
columnas_esperadas = [
    'UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234',
    'UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238',
    'UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243',
    'UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247',
    'UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260',
    'UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264',
    'UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455',
    'UsodeDisp_6457',
    'QtyCamiones_DESCANSO','Disponibilidad_TKS_DESCANSO',
    'UsodeDisp_TKS_DESCANSO','TiempoCiclo_TKS_DESCANSO',
    'QtyCamiones_DP5','Disponibilidad_TKS_DP5',
    'UsodeDisp_TKS_DP5','TiempoCiclo2_DP5',
    'QtyCamiones_EC','Disponibilidad_TKS_EC',
    'UsodeDisp_TKS_EC','TiempoCiclo2_EC',
    'QtyCamiones_PRIBBENOW','Disponibilidad_TKS_PRIBBENOW',
    'UsodeDisp_TKS_PRIBBENOW','TiempoCiclo_TKS_PRIBBENOW',
    'turno'
]

data = data[columnas_esperadas]

# Preview opcional
st.subheader('Vista previa de los datos ingresados')
st.dataframe(data.T.rename(columns={0: 'Valor'}))

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['turno'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','QtyCamiones_DESCANSO','Disponibilidad_TKS_DESCANSO','UsodeDisp_TKS_DESCANSO','TiempoCiclo_TKS_DESCANSO','QtyCamiones_DP5','Disponibilidad_TKS_DP5','UsodeDisp_TKS_DP5','TiempoCiclo2_DP5','QtyCamiones_EC','Disponibilidad_TKS_EC','UsodeDisp_TKS_EC','TiempoCiclo2_EC','QtyCamiones_PRIBBENOW','Disponibilidad_TKS_PRIBBENOW','UsodeDisp_TKS_PRIBBENOW','TiempoCiclo_TKS_PRIBBENOW']]= min_max_scaler.transform(data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','QtyCamiones_DESCANSO','Disponibilidad_TKS_DESCANSO','UsodeDisp_TKS_DESCANSO','TiempoCiclo_TKS_DESCANSO','QtyCamiones_DP5','Disponibilidad_TKS_DP5','UsodeDisp_TKS_DP5','TiempoCiclo2_DP5','QtyCamiones_EC','Disponibilidad_TKS_EC','UsodeDisp_TKS_EC','TiempoCiclo2_EC','QtyCamiones_PRIBBENOW','Disponibilidad_TKS_PRIBBENOW','UsodeDisp_TKS_PRIBBENOW','TiempoCiclo_TKS_PRIBBENOW']])
data_preparada.head()

"""##**PREDICCIONES**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 1.5%")